- name: download redis
  get_url:
    url: http://download.redis.io/releases/redis-3.0.7.tar.gz
    dest: ~/{{tmp_dir}}
    force: no

- name: unarchive redis
  unarchive:
    src: ~/{{tmp_dir}}/redis-3.0.7.tar.gz
    dest: ~/{{tmp_dir}}
    mode: 0755
    copy: no
    creates: ~/{{tmp_dir}}/redis-3.0.7

- name: install redis
  shell: make -j 4 && make PREFIX=$HOME/redis-3.0.7 install
  args:
    chdir: ~/{{tmp_dir}}/redis-3.0.7
    creates: ~/redis-3.0.7
