- name: setup simple
  hosts: user
  connection: local
  vars:
    - tmp_dir: tmp
    - vim_version: 8.1.1735
  roles:
    # - common
    - vim
    # - ctags
    # - redis
    # - cmake
    # - mysql
    # - nvm
    # - node
    # - autoconf
    # - automake
    # - screen
