- name: download ctags
  get_url:
    url: http://prdownloads.sourceforge.net/ctags/ctags-5.8.tar.gz
    dest: ~/{{tmp_dir}}
    force: no

- name: unarchive ctags
  unarchive:
    src: ~/{{tmp_dir}}/ctags-5.8.tar.gz
    dest: ~/{{tmp_dir}}
    mode: 0755
    copy: no
    creates: ~/{{tmp_dir}}/ctags-5.8

- name: install ctags
  shell: ./configure --prefix=$HOME/ctags-5.8 && make && make install
  args:
    chdir: ~/{{tmp_dir}}/ctags-5.8
    creates: ~/ctags-5.8

