- name: download global
  get_url:
    url: http://tamacom.com/global/global-6.5.2.tar.gz
    dest: ~/{{tmp_dir}}
    force: no

- name: unarchive global
  unarchive:
    src: ~/{{tmp_dir}}/global-6.5.2.tar.gz
    dest: ~/{{tmp_dir}}
    mode: 0755
    copy: no
    creates: ~/{{tmp_dir}}/global-6.5.2

- name: install Pygments
  pip:
    name: Pygments

- name: install global
  shell: ./configure --prefix=$HOME/global-6.5.2 && make && make install
  args:
    chdir: ~/{{tmp_dir}}/global-6.5.2
    creates: ~/global-6.5.2

