- name: unarchive mysql
  unarchive:
    src: http://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.9.tar.gz
    dest: ~/{{tmp_dir}}
    mode: 0755
    copy: no
    creates: ~/{{tmp_dir}}/mysql-5.7.9

- name: install mysql
  shell: |
    PATH=$HOME/cmake-3.5.2/bin:$PATH
    cmake . -DCMAKE_INSTALL_PREFIX=$HOME/mysql-5.7.9 \
            -DDEFAULT_CHARSET=utf8 \
            -DDEFAULT_COLLATION=utf8_general_ci \
            -DMYSQL_DATADIR=$HOME/mysql-5.7.9/var/mysql \
            -DMYSQL_UNIX_ADDR=$HOME/mysql-5.7.9/tmp/mysql.sock \
            -DSYSCONFDIR=$HOME/mysql-5.7.9/etc \
            -DTMPDIR=$HOME/mysql-5.7.9/tmp \
            -DWITH_INNOBASE_STORAGE_ENGINE=1 \
            -DDOWNLOAD_BOOST=1 \
            -DWITH_BOOST=$HOME/boost
    make -j 4 && make install
  args:
    chdir: ~/{{tmp_dir}}/mysql-5.7.9
    creates: ~/mysql-5.7.9

- name: create a var directory
  file:
    path: ~/mysql-5.7.9/var/mysql
    state: directory

- name: create a tmp directory
  file:
    path: ~/mysql-5.7.9/tmp
    state: directory

- name: create a etc directory
  file:
    path: ~/mysql-5.7.9/etc
    state: directory

- copy: src=~/mysql-5.7.9/support-files/my-default.cnf dest=~/mysql-5.7.9/etc/my.cnf
# mysqld --initialize
# mysqld > /dev/null 2>&1 &
# mysql -uroot -p
# set password for root@localhost=password('newpassword');
# mysqladmin -uroot -p shutdown
