- name: download automake
  get_url:
    url: http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
    dest: ~/{{tmp_dir}}

- name: unarchive automake
  unarchive:
    src: ~/{{tmp_dir}}/automake-1.15.tar.gz
    dest: ~/{{tmp_dir}}
    mode: 0755
    copy: no
    creates: ~/{{tmp_dir}}/automake-1.15

- name: install automake
  shell: PATH=$HOME/autoconf-2.69/bin:$PATH; ./configure --prefix=$HOME/automake-1.15 && make -j 4 && make install
  args:
    chdir: ~/{{tmp_dir}}/automake-1.15
    creates: ~/automake-1.15
